stages:
  - build
  - release

build-windows:
  stage: build
  tags: ["windows"]
  script:
    - py -3 -m pip install --upgrade pip
    - py -3 -m pip install -e .
    - py -3 -m pip install pyinstaller
    - powershell -ExecutionPolicy Bypass -File scripts/build_exe.ps1 -Name "SenseisUpdater"
  artifacts:
    paths:
      - dist/SenseisUpdater.exe
    expire_in: 2 weeks

release:
  stage: release
  needs: ["build-windows"]
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "Releasing $CI_COMMIT_TAG"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
  release:
    name: '$CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    description: 'Release $CI_COMMIT_TAG'
    assets:
      links:
        - name: 'SenseisUpdater.exe'
          url: '$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/dist/SenseisUpdater.exe'