name: build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  windows-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install pyinstaller

      - name: Clean old spec and artifacts
        shell: pwsh
        run: |
          if (Test-Path "SenseisUpdater.spec") { Remove-Item -Force "SenseisUpdater.spec" }
          Remove-Item -Recurse -Force build, dist -ErrorAction SilentlyContinue | Out-Null

      - name: Build EXE
        shell: pwsh
        run: powershell -ExecutionPolicy Bypass -File scripts/build_exe.ps1 -Name "SenseisUpdater"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SenseisUpdater-Windows
          path: dist/SenseisUpdater.exe