name: build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  windows-exe:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller

      - name: Build EXE (PyInstaller)
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force build, dist -ErrorAction SilentlyContinue | Out-Null
          python -m PyInstaller --noconfirm --clean --onefile --name "SenseisUpdater" --console src/sensei_updater/app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SenseisUpdater-Windows
          path: dist/SenseisUpdater.exe